#ifndef FW_CONFIG_H
#define FW_CONFIG_H

#define FW_IS_FULLSCREEN_ENABLED TRUE
#define FW_IS_FULLSCREEN_BORDERLESS_ENABLED FALSE

#define FW_IS_MUSIC_ENABLED TRUE

#define FW_WINDOW_NAME  "GLEN-Z - SPECTROX"

#define FW_WINDOW_WIDTH  692
#define FW_WINDOW_HEIGHT 540

#define FW_RENDER_WIDTH  346
#define FW_RENDER_HEIGHT 270

#define FW_STARTUP_DELAY_MILLIS 0

#endif
